name: Run pipeline(s)

on:
  workflow_dispatch:
    inputs:
      env:
        description: "The github environment to use."
        required: true
        type: choice
        options:
          - develop
          - stage

jobs:
  run_pipeline:
    environment: ${{ github.event.inputs.env }}
    name: Run Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: read env variables
        env:
          SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
          WIF: ${{ vars.WORKFLOW_IDENTITY_PROVIDER }}
        shell: bash
        run: |
          echo "service account : $serviceAccount"
          echo "workflow identity provider : $wif"
